language: rust

rust:
  - nightly
  - stable
  - beta
  - 1.30.0

matrix:
  include:
    - rust: nightly
      name: Minimal versions
      script:
        - cargo update -Z minimal-versions
        - cargo check
    - rust: nightly
      name: Clippy
      script: |
          if rustup component add clippy-preview; then
              cargo clippy --tests -- -D clippy::all
          fi
