language: rust

rust:
  - nightly
  - stable
  - beta
  - 1.26.0

matrix:
  include:
    - rust: nightly
      env: MINIMAL
      script:
        - cargo update -Z minimal-versions
        - cargo check
    - rust: nightly
      env: CLIPPY
      script: |
          if rustup component add clippy-preview; then
              cargo clippy --tests -- -D clippy::all
          fi
