[package]
name = "mini-internal"
version = "0.1.12"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Derive macros for miniserde. Use the re-exports from the miniserde crate instead."
repository = "https://github.com/dtolnay/miniserde"
documentation = "https://docs.rs/miniserde"
edition = "2018"

[lib]
proc-macro = true

[badges]
travis-ci = { repository = "dtolnay/miniserde" }

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.2"
syn = "1.0"
