[package]
name = "mini-internal"
version = "0.1.3"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Derive macros for miniserde. Use `#[macro_use] extern crate miniserde` instead."
repository = "https://github.com/dtolnay/miniserde"
documentation = "https://docs.rs/miniserde"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
